#Vincent Nambatac
---

# Set timezone to Asia/Manila to all hosts
- hosts: kafka
  become: true
  become_method: sudo
  gather_facts: False
  tasks:

  - name: Set timezone to Asia/Manila
    community.general.timezone:
      name: Asia/Manila

- hosts: zookeeper
  become: true
  gather_facts: False
  tasks:

  - name: Set timezone to Asia/Manila
    community.general.timezone:
      name: Asia/Manila


    
# PREPARE Kafka environments and dependencies

- hosts: kafka
  become: true
  become_method: sudo
  gather_facts: False 
  vars_files:
    - vars/settings.yaml

  tasks:
  - name: Update ubuntu package
    command: apt update

  - name: 'Install JVM: {{ jvm_package }}'
    apt:
      name: openjdk-11-jdk
      state: latest

  - name: Create group "{{ kafka_user }}" 
    group:
      name: "{{ kafka_user }}"
      state: present

  - name: Create user '{{ kafka_user }}'
    user:
      name: "{{ kafka_user }}"
      password: "{{ 'kafka@pass' | password_hash('sha512','A512') }}"
      group: "{{ kafka_user }}"

  - name: sudo without password for kafka group
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%{{ kafka_user }}'
      line: '{{ kafka_user }}	ALL=(ALL:ALL) ALL'
      validate: 'visudo -cf %s'

  - name: add kafka:kafka to list of sudoers
    shell: |
      usermod -aG sudo kafka


  - name: "Create installation folder {{ kafka_install_package_host_folder }}"
    file:
      path: "{{ kafka_install_package_host_folder }}"
      state: directory
      mode: 0755
      group: "{{ kafka_user }}"
      owner: "{{ kafka_user }}" 

  - name: Copy kafka package to remote server
    copy: src={{kafka_install_package_source_folder}}/{{ kafka_install_package_name }} dest={{ kafka_install_package_host_folder }} mode=0777
    become: yes

  - name: Unzip kafka package "{{ kafka_install_package_host_folder }}/{{ kafka_install_package_name }}"
    unarchive:
      src: /opt/redhat/kafka_2.13-2.8.0.tgz
      dest: /opt/redhat
      remote_src: yes
      list_files: yes
    register: unarchived_list

  - name: Removing {{ kafka_install_package_host_folder }}/{{ kafka_install_package_name }}
    file:
      path: "{{ kafka_install_package_host_folder }}/{{ kafka_install_package_name }}"
      state: absent      
    become: yes

  - name: Create symbolic link {{ kafka_install_host_symlink }} for {{kafka_install_package_host_folder}}/kafka_2.13-2.8.0
    file:
      src: "{{kafka_install_package_host_folder}}/kafka_2.13-2.8.0"
      dest: "/opt/kafka"
      state: link 

  - name: Change user and group for symblink {{ kafka_install_host_symlink }}
    command: chown -R kafka:kafka {{ kafka_install_host_symlink }}
    become: true 

  - name: Set KAFKA_HOME={{ kafka_install_host_symlink }} in  /home/{{ kafka_user }}/.bashrc
    ansible.builtin.lineinfile: 
      dest: /home/{{ kafka_user }}/.bashrc
      line: "export KAFKA_HOME={{ kafka_install_host_symlink }}"
  - name: Set JAVA_HOME={{ kafka_user }} in /home/{{ kafka_user }}/.bashrc
    lineinfile:
      dest: /home/{{ kafka_user }}/.bashrc
      line: "export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64/"

  - name: source bashrc
    action: shell . /home/{{ kafka_user }}/.bashrc && ls -ltr
    become: true

##  SET ZOOKEEPER SERVERS
#
- hosts: zookeeper
  become: yes
  user: root
  gather_facts: False
  vars_files:
    - vars/settings.yaml
  
  tasks:

  - name: Create group "{{ zookeeper_user }}"
    group:
      name: "{{ zookeeper_user }}"
      state: present
    tags:
      - group
  - name: sudo without password for zk group
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%{{ zookeeper_user }}'
      line: '{{ zookeeper_user }}    ALL=(ALL:ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Create user '{{ zookeeper_user }}'
    user:
      name: "{{ zookeeper_user }}"
      password: "{{ 'zk@pass' | password_hash('sha512','A512') }}"
      group: "{{ zookeeper_user }}"
      append: yes
      state: present
      createhome: yes
    tags:
      - user

  - name: "Create data folder for zookeeper {{ zookeeper_data_dir }}"
    file:
      path: "{{ zookeeper_data_dir }}"
      state: directory
      mode: 0755
      group: "{{ zookeeper_user }}"
      owner: "{{ zookeeper_user }}"
    tags:
      - data

  - name: Update ubuntu package
    command: apt update
    tags:
      - update
  - name: 'Install JVM: {{ jvm_package }}'
    apt:
      name: openjdk-11-jdk
      state: latest
    tags:
      - jvm
  - name: Set JAVA_HOME={{ zookeeper_user }} in /home/{{ zookeeper_user }}/.bashrc
    lineinfile:
      dest: /home/{{ zookeeper_user }}/.bashrc
      line: "export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64/" 

  - name: Set ZK_HOME={{ zookeeper_user }} in /home/{{ zookeeper_user }}/.bashrc
    lineinfile:
      dest: /home/{{ zookeeper_user }}/.bashrc
      line: "export ZK_HOME=/opt/zookeeper"

  - name: source bashrc
    action: shell . /home/{{ zookeeper_user }}/.bashrc && ls -ltr
    become: true


  - name: "Create installation folder {{ zookeeper_install_package_host_folder }}"
    file:
      path: "{{ zookeeper_install_package_host_folder }}"
      state: directory
      mode: 0755
      group: "{{ zookeeper_user }}"
      owner: "{{ zookeeper_user }}"
    tags:
      - folder

  - name: "Create data folder for zookeeper {{ zookeeper_log_dir }}"
    file:
      path: "{{ zookeeper_log_dir }}"
      state: directory
      mode: 0755
      group: "{{ zookeeper_user }}"
      owner: "{{ zookeeper_user }}"    

  - name: Copy zookeeper package to zookeeper_servers
    copy: src={{ zookeeper_install_package_source_folder }}/{{ zookeeper_installation_package }} dest={{ zookeeper_install_package_host_folder }}
    become: yes
    tags:
      - copy

  - name: "Unzip zookeeper package {{ zookeeper_installation_package }} "
    unarchive:
      src: "{{ zookeeper_install_package_host_folder }}/{{ zookeeper_installation_package }}"
      dest: "{{ zookeeper_install_package_host_folder }}"
      remote_src: yes
      list_files: yes
    register: unarchive_lists
    tags:
      - unzip

  - name: Removing {{ zookeeper_install_package_host_folder }}/{{ zookeeper_installation_package }}
    file:
      path: "{{ zookeeper_install_package_host_folder }}/{{ zookeeper_installation_package }}"
      state: absent
    tags:
      - remove

  - name: Create symbolic link {{ zookeeper_sym_link }} for {{zookeeper_install_package_host_folder}}/apache-zookeeper-3.7.0-bin 
    file:
      src: "{{zookeeper_install_package_host_folder}}/apache-zookeeper-3.7.0-bin"
      dest: "/opt/zookeeper"
      state: link
    tags:
      - link

  - name: Change user and group for symblink {{ zookeeper_sym_link }}
    command: sudo chown -R zk:zk /opt/zookeeper/
    become: true

  - name: Change user and group for data dir {{ zookeeper_data_dir }}
    command: chown -R zk:zk /data/zookeeper/
    become: true

  - name: create file for zoo.cfg
    file:
      state: touch
      path : "{{ zookeeper_sym_link }}/conf/zoo.cfg"

  - name: Create file zookeeper.properties
    template:
      src: templates/zookeeper-properties.j2
      dest: "{{ zookeeper_sym_link }}/conf/zoo.cfg"      
      mode: 0644
    tags:
      - properties

  - name: Create file zookeeper.service
    template:
      src: templates/zookeeper.j2
      dest: /etc/systemd/system/zookeeper.service      
      mode: 0755
    tags:
      - service

  - name: Create myid file and insert the node id.
    lineinfile:
      path: "{{ zookeeper_data_dir }}/myid"
      line: "{{ groups.zookeeper.index(inventory_hostname)+1 }}"
      create: yes
    tags:
      - id

  - name: "Create data folder for node exporter to {{ zookeeper_node_exporter }}"
    file:
      path: "{{ zookeeper_node_exporter }}"
      state: directory
      mode: 0755
      group: "{{ zookeeper_user }}"
      owner: "{{ zookeeper_user }}"
  
  - name: "Install node_exporter to zookeeper clusters"
    get_url:
      url="https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz"
      dest={{ zookeeper_node_exporter }}

  - name: "Unzip node_exporter-1.1.2.linux-amd64.tar.gz to {{ zookeeper_node_exporter }}"
    unarchive:
      src: "{{ zookeeper_node_exporter }}/node_exporter-1.1.2.linux-amd64.tar.gz"
      dest: "{{ zookeeper_node_exporter }}"
      remote_src: yes
      list_files: yes

  - name: "Remove package node_exporter-1.1.2.linux-amd64.tar.gz from {{ zookeeper_node_exporter }}"
    file:
      path: "{{ zookeeper_node_exporter }}/node_exporter-1.1.2.linux-amd64.tar.gz"
      state: absent

  - name: " Move node_exporter-1.1.2.linux-amd64 content to /opt/node_exporter directory"
    shell: |
      cd /opt/node_exporter && mv node_exporter-1.1.2.linux-amd64/* /opt/node_exporter
      rm -r /opt/node_exporter/node_exporter-1.1.2.linux-amd64

  - name: Create node_exporter.service
    template:
      src: templates/zookeeper_node_exporter.j2
      dest: /etc/systemd/system/node_exporter.service
      mode: 0755

  - name: set zk:zk owner for /data/zookeeper/*
    shell: |
      chown -R zk:zk /data/*


  - name: just force systemd to reread configs (2.4 and above)
    systemd:
      daemon_reload: yes
    tags:
      - force

  - name: enable service zookeeper.service and ensure it is not masked
    systemd:
      name: zookeeper.service
      enabled: yes
      masked: no    
    tags:
      - enable
  - name: enable service node_exporter.service and ensure it is not masked
    systemd:
      name: node_exporter.service
      enabled: yes
      masked: no

  - name: set zk:zk as owner /opt/zookeeper
    shell: |
      chown -R zk:zk /opt/zookeeper/*


  - name: Start zookeeper
    service:
      name: zookeeper.service
      state: restarted     
    tags:
      - start


  - name: Start node_exporter.service
    service:
      name: node_exporter.service
      state: restarted

##  SET KAFKA BROKERS     

- hosts: kafka  
  vars_files:
     - vars/settings.yaml

  tasks: 

  - name: "Create data folder for kafka {{ kafka_log_dirs }}"
    file:
      path: "{{ kafka_log_dirs }}"
      state: directory
      mode: 0755
      group: "{{ kafka_user }}"
      owner: "{{ kafka_user }}"       

  - name: Create file {{ kafka_install_host_symlink }}/config/server.properties
    template:
      src: templates/server-properties.j2
      dest: "{{ kafka_install_host_symlink }}/config/server.properties"         
      mode: 0644

  - set_fact: 
      zookeeper_connect: "{{ groups.zookeeper | join(':{{ zookeeper_port }},') }}:{{ zookeeper_port }}"
      rendered_template: "{{ lookup('template', 'templates/server-properties.j2') }}"

  - name: Set zookeeper hosts in server.properties
    replace:
      path: "{{ kafka_install_host_symlink }}/config/server.properties"
      regexp: 'zookeeper.connect=localhost:2181'
      replace: "zookeeper.connect={{ zookeeper_connect }}/apollo-kafka1"

  - name: Create file kafka.service
    template:
      src: templates/kafka.j2
      dest: /etc/systemd/system/kafka.service      
      mode: 0755


  - name: "Create data folder for Jolokia {{ kafka_jolokia_folder }}"
    file:
      path: "{{ kafka_jolokia_folder }}"
      state: directory
      mode: 0755
      group: "{{ kafka_user }}"
      owner: "{{ kafka_user }}"

  - name: "Install Jolokia jar file to {{ kafka_jolokia_folder }}"
    shell: |
      cd /opt/jolokia
      wget https://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-jvm/1.6.2/jolokia-jvm-1.6.2-agent.jar -O jolokia-agent.jar


  - name: "Set data folder for prometheus {{ kafka_prometheus_folder }}"
    file:
      path: "{{ kafka_prometheus_folder }}"
      state: directory
      mode: 0755
      group: "{{ kafka_user }}"
      owner: "{{ kafka_user }}"

  - name: "Install jmx exporter {{ kafka_prometheus_folder }}"
    get_url:
      url="https://repo1.maven.org/maven2/io/prometheus/jmx/jmx_prometheus_javaagent/0.16.0/jmx_prometheus_javaagent-0.16.0.jar"
      dest="{{ kafka_prometheus_folder }}/jmx_prometheus_javaagent-0.16.0.jar"

  - name: "Create data folder for node exporter to {{ kafka_node_exporter }}"
    file:
      path: "{{ kafka_node_exporter }}"
      state: directory
      mode: 0755
      group: "{{ kafka_user }}"
      owner: "{{ kafka_user }}"

  - name: "Install node_exporter to kafka brokers"
    get_url:
      url="https://github.com/prometheus/node_exporter/releases/download/v1.1.2/node_exporter-1.1.2.linux-amd64.tar.gz"
      dest={{ kafka_node_exporter }}

  - name: "Unzip node_exporter-1.1.2.linux-amd64.tar.gz to {{ kafka_node_exporter }}"
    unarchive:
      src: "{{ kafka_node_exporter }}/node_exporter-1.1.2.linux-amd64.tar.gz"
      dest: "{{ kafka_node_exporter }}"
      remote_src: yes
      list_files: yes


  - name: "Remove package node_exporter-1.1.2.linux-amd64.tar.gz from {{ kafka_node_exporter }}"
    file:
      path: "{{ kafka_node_exporter }}/node_exporter-1.1.2.linux-amd64.tar.gz"
      state: absent
  - name: " Move node_exporter-1.1.2.linux-amd64 content to /opt/node_exporter directory"
    shell: |
      cd /opt/node_exporter && mv node_exporter-1.1.2.linux-amd64/* /opt/node_exporter
      rm -r /opt/node_exporter/node_exporter-1.1.2.linux-amd64

  - name: "Install config to {{ kafka_prometheus_folder }}"
    shell: |
      cd /opt/prometheus && wget https://raw.githubusercontent.com/prometheus/jmx_exporter/master/example_configs/kafka-2_0_0.yml
  
  - name: Rename kafka-2_0_0.yml to kafka-2.yml
    shell: |
      cd /opt/prometheus && touch kafka-2.yml
      cd /opt/prometheus && mv kafka-2_0_0.yml kafka-2.yml    

  - name: Create node_exporter.service
    template:
      src: templates/kafka_node_exporter.j2
      dest: /etc/systemd/system/node_exporter.service
      mode: 0755
 

  - name: set kafka:kafka as owner to /opt/*
    shell: |
      chown -R kafka:kafka /opt/*

  - name: Force systemd to reread configs (2.4 and above)
    systemd:
      daemon_reload: yes

  - name: enable node_exporter.service and ensure it is not masked
    systemd:
      name: node_exporter.service
      enabled: yes
      masked: no

  - name: Enable service kafka.service and ensure it is not masked
    systemd:
      name: kafka.service
      enabled: yes
      masked: no        

  - name: Start kafka
    service:
      name: kafka.service
      state: restarted

  - name: Start node_exporter
    service:
      name: node_exporter.service
      state: restarted

